export default [
    {
        id: "1",
        place: 'Dubai',
        price: '2000',
        description: 'Enjoy an unforgettable excursion to Dubai, a city where modern innovation meets rich cultural heritage. Marvel at the breathtaking Burj Khalifa, the tallest building in the world, and indulge in luxury shopping at the famous Dubai Mall. Experience the charm of Old Dubai with its traditional souks and historical districts. Embark on a thrilling desert safari, where you can ride camels, try sandboarding, and enjoy an authentic Arabian dinner under the stars. Relax on the stunning beaches or explore the world-class entertainment at Palm Jumeirah. Dubai offers a perfect blend of adventure, luxury, and culture for an extraordinary travel experience.',
        imageUrl: '/static/img/dubai.jpg',
        purpose: 'educate',
        year: '2021',
        rating: 6.6,
        transport: 'Airplane',
    },
    {
        id: "2",
        place: 'Maldives',
        price: '5000',
        description: 'Escape to the Maldives, a breathtaking tropical paradise with crystal-clear waters and pristine white sandy beaches. Stay in luxurious overwater villas and wake up to the soothing sounds of the ocean. Explore vibrant coral reefs while snorkeling or diving, discovering a mesmerizing underwater world. Indulge in exquisite seafood and relax with rejuvenating spa treatments by the sea. Whether you seek adventure or tranquility, the Maldives offers the perfect island getaway.',
        imageUrl: '/static/img/maldivi.jpg',
        purpose: 'chil',
        year: '2013',
        rating: 7.1,
        transport: 'Airplane',
    },
    {
        id: "6b3677b9-2798-4a60-95b9-966fdfe68e81",
        place: 'Thailand',
        price: '6000',   
        description: 'Embark on an unforgettable excursion to Thailand, a land of stunning beaches, rich culture, and exotic flavors. Explore the bustling streets of Bangkok, the ancient temples of Ayutthaya, and the breathtaking islands of Phuket and Krabi. Experience vibrant nightlife, delicious Thai cuisine, and the warm hospitality of this tropical paradise.',
        imageUrl: '/static/img/thailand.jpg',
        purpose: 'bissnes',
        year: '2019',
        rating: 8.4,
        transport: 'Airplane',
    },
] 